### ISSUE TITLE
please accept https://github.com/nzbget/nzbget/pull/765 : updated posix/config.guess and posix/config.sub

### ISSUE THREAD

**Issue by sanderjo** [nzbget-ng/nzbget#14]
Can you please accept https://github.com/nzbget/nzbget/pull/765 which solves https://github.com/nzbget/nzbget/issues/755 

With that PR, the ./configure works on riscv64

**Comment by paul-chambers** [comment]
Those files are generated as part of the `autoreconf` process, and shouldn't have been checked in in the first place (along with a few other files). I recently removed these intermediate artifacts from the repo.

Try a fresh checkout, and run the '`rebuild.sh`' script, which should (re)generate those files correctly for your environment.

Let me know how it goes (I don't have access to a riscv64 platform to reproduce this).

**Comment by sanderjo** [comment]
Yes, works!
Thanks.
