### ISSUE TITLE
Current develop branch doesn't queue nzb's, git bisect results included.

### ISSUE THREAD

**Issue by bacon-cheeseburger** [nzbget-ng/nzbget#40]
Hi,
I just switched from the dead nzbget github to nzbget-ng develop branch. I normally add nzb's by putting the *.nzb files into a monitored `incoming` directory. After compiling the current develop branch, nzb's no longer get queued and downloaded. The results of a git bisect are:

> a70a383c9db50cc5b5f122cc5a52ec4dc9c9abd7 is the first bad commit
>
>commit a70a383c9db50cc5b5f122cc5a52ec4dc9c9abd7
>Author: Paul Chambers <projects@bod.org>
>Date:   Fri Mar 3 21:58:01 2023 -0800
>
>   Nuke duplicated includes, add string.h
>
> daemon/main/nzbget.h | 8 +++-----
> 1 file changed, 3 insertions(+), 5 deletions(-)

If I `git reset --soft 53de515235aaedc621a9cfd5cc83b17764436f37`, which is the commit prior, everything works. Any idea why the above commit breaks queue'ing/downloading?

**Comment by paul-chambers** [comment]
No idea - very strange. That commit was literally removing a couple of headers that were included twice, and adding 'string.h', which is unlikely to cause problems, given how ubiquitous it is.

Did you do a clean rebuild? one of the things I've run into with autotools is that it's not too smart when things change under its feet.

**Comment by bacon-cheeseburger** [comment]
Yup, was a clean. It's not obvious to me why that commit causes a problem. I feel like it's something small and that's why but I dunno.

**Comment by pannal** [comment]
Same issue here, sonarr complains about aborted connections and doesn't seem to queue in nzbget anymore.

**Comment by bacon-cheeseburger** [comment]
Still no idea on this bug?

**Comment by lainedfles** [comment]
I don't see this problem with my configuration on Archlinux which includes btrfs + dedicated limited user. Built using the [AUR](https://aur.archlinux.org/packages/nzbget-git) [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nzbget-git) which executes:
```
build() {
  cd "$srcdir/$pkgname"

  autoreconf --install
  ./configure --prefix=/usr --sbindir='/usr/bin' --enable-parcheck --with-tlslib=OpenSSL
  make
}
```
I do set `MainDir=` to a shared directory with permissions permitting group membership including my desktop user. Otherwise any NZB that I drop into `NzbDir=${MainDir}/nzb` is eventually downloaded automatically.

Could this be an OS or build configuration discrepancy?

**Comment by bacon-cheeseburger** [comment]
It seems my original bisect was faulty, though I'm not sure how that happened. Anyway, I redid it and found the breaking commit to be 8ca0364a5891f6d032c50d57369b9dee9620f863 ("fix minor compiler warnings, code cleanup"). Further, it's the change to daemon/util/Script.cpp that causes the break. If I grab a fresh clone, revert just that part of that commit, nzb's get queued and download as expected.

**Comment by bacon-cheeseburger** [comment]
@paul-chambers 

It seems my original bisect was faulty, though I'm not sure how that happened. Anyway, I redid it and found the breaking commit to be 8ca0364a5891f6d032c50d57369b9dee9620f863 ("fix minor compiler warnings, code cleanup"). Further, it's the change to daemon/util/Script.cpp that causes the break. If I grab a fresh clone, revert just that part of that commit, nzb's get queued and download as expected.

Will you please have a look using this new information?
