### ISSUE TITLE
Non-latin characters become underscores after archives' extraction

### ISSUE THREAD

**Issue by awsms** [nzbget-ng/nzbget#42]
Once nzbget finished downloading and starts extracing in an _unpack folder, any korean, hebrew, japanese, arabic etc letter in the filenames becomes an _.
This is not because of defective archives, since the filenames are perfectly fine if I manually extract the archives.

**Comment by paul-chambers** [comment]
It would help if you indicated what platform and version you're running... along with the log information. Also the versions of any helper executables that nzbget is configured to use, particularly if different from the ones in your normal path.

As this report stands, there are too many variables to be able to reproduce your problem. An example NZB would also be useful - I'm assuming the filenames in question are UTF-8 encoded? Are the filenames explicit in the NZB, or are PAR2 files required to rename them?

Are you using nzbget with one or more of the *arrs? You're seeing this using nzbget standalone, correct?

**Comment by awsms** [comment]
Sorry about the lack of info, I had this issue on all the Linux machines I tried the program on.
I'm currently running Ubuntu 22.04, standalone nzbget (21.1), unrar (6.11 beta 1 freeware). Files do not require pars or any rename scripts.

https://krakenfiles.com/view/AdY7YpBql6/file.html extraction password is ``nZbG3T``

**Comment by awsms** [comment]
Nevermind, nzbget was using a provided & out-of-date version of unrar (5.70) instead of the one provided by the package manager. Setting unrar to its full path fixed this issue!
