### ISSUE TITLE
server selection should skip inactive servers

### ISSUE THREAD

**Issue by philon123** [nzbget-ng/nzbget#55]
If I have a disabled priority 0 server and an enabled priority 1 server, currently nothing gets downloaded, it just hangs. I suppose it's waiting for the priority 0 server somehow? Obviously, that doesn't make sense, it should skip that server since it's disabled and move on to the priority 1 server immediately.

**Comment by paul-chambers** [comment]
Cloned to https://github.com/nzbgetcom/nzbget/issues/95, so closing here.
